<Project>
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <Deterministic>true</Deterministic>
    <PreferredToolArchitecture>x64</PreferredToolArchitecture>
    <SpectreMitigation>Spectre</SpectreMitigation>
  </PropertyGroup>

  <ItemDefinitionGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <ClCompile>
      <WarningLevel>Level4</WarningLevel>
      <TreatWarningAsError>true</TreatWarningAsError>
      <SDLCheck>true</SDLCheck>
      <CompileAs>CompileAsC</CompileAs>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
