#pragma once

#include <ntddk.h>
#include <wdf.h>

#include "ChatpadKmdfRequestOwnerContext.h"

#define CHATPAD_RUNTIME_TRACE_PROVIDER_GUID_STRING \
    "{1B3D3598-9D78-4F3E-9DB2-95BB9344A731}"
#define CHATPAD_RUNTIME_TRACE_SCHEMA_VERSION ((ULONG)1u)

#define WPP_CONTROL_GUIDS \
    WPP_DEFINE_CONTROL_GUID( \
        ChatpadRuntimeTraceGuid, \
        (1B3D3598,9D78,4F3E,9DB2,95BB9344A731), \
        WPP_DEFINE_BIT(CHATPAD_TRACE_DRIVER_ENTRY) \
        WPP_DEFINE_BIT(CHATPAD_TRACE_DEVICE_ADD) \
        WPP_DEFINE_BIT(CHATPAD_TRACE_OWNER) \
        WPP_DEFINE_BIT(CHATPAD_TRACE_ORCHESTRATION) \
        WPP_DEFINE_BIT(CHATPAD_TRACE_READINESS) \
        WPP_DEFINE_BIT(CHATPAD_TRACE_LIFECYCLE) \
        WPP_DEFINE_BIT(CHATPAD_TRACE_CLEANUP) \
        WPP_DEFINE_BIT(CHATPAD_TRACE_PROHIBITED_COUNTERS) \
        WPP_DEFINE_BIT(CHATPAD_TRACE_INVARIANT) \
        WPP_DEFINE_BIT(CHATPAD_TRACE_TERMINAL))

#define WPP_FLAG_LEVEL_LOGGER(flag, level) WPP_LEVEL_LOGGER(flag)
#define WPP_FLAG_LEVEL_ENABLED(flag, level) \
    (WPP_LEVEL_ENABLED(flag) && WPP_CONTROL(WPP_BIT_ ## flag).Level >= level)
#define WPP_LEVEL_FLAGS_LOGGER(level, flags) WPP_LEVEL_LOGGER(flags)
#define WPP_LEVEL_FLAGS_ENABLED(level, flags) \
    (WPP_LEVEL_ENABLED(flags) && WPP_CONTROL(WPP_BIT_ ## flags).Level >= level)

/*
begin_wpp config
FUNC ChatpadTrace(LEVEL, FLAGS, MSG, ...);
USEPREFIX (ChatpadTrace, "%!STDPREFIX! [%!FUNC!] ");
end_wpp
*/

typedef enum ChatpadRuntimeTraceEventId {
    CHATPAD_RUNTIME_EVENT_DRIVER_ENTRY_STARTED = 1000,
    CHATPAD_RUNTIME_EVENT_WDF_DRIVER_CREATE_ATTEMPTED = 1001,
    CHATPAD_RUNTIME_EVENT_WDF_DRIVER_CREATE_FAILED = 1002,
    CHATPAD_RUNTIME_EVENT_DRIVER_ENTRY_COMPLETED = 1003,
    CHATPAD_RUNTIME_EVENT_DEVICE_ADD_ENTERED = 1100,
    CHATPAD_RUNTIME_EVENT_DEVICE_CREATE_ATTEMPTED = 1101,
    CHATPAD_RUNTIME_EVENT_DEVICE_CREATE_FAILED = 1102,
    CHATPAD_RUNTIME_EVENT_DEVICE_CONTEXT_INITIALIZING = 1103,
    CHATPAD_RUNTIME_EVENT_DEVICE_CONTEXT_READY = 1104,
    CHATPAD_RUNTIME_EVENT_DEVICE_CREATE_COMPLETED = 1105,
    CHATPAD_RUNTIME_EVENT_OWNER_STORAGE_INIT_STARTED = 1200,
    CHATPAD_RUNTIME_EVENT_OWNER_STORAGE_INIT_COMPLETED = 1201,
    CHATPAD_RUNTIME_EVENT_OWNER_STORAGE_INIT_FAILED = 1202,
    CHATPAD_RUNTIME_EVENT_PRE_OBJECT_VALIDATION_STARTED = 1203,
    CHATPAD_RUNTIME_EVENT_PRE_OBJECT_VALIDATION_FAILED = 1204,
    CHATPAD_RUNTIME_EVENT_PRE_OBJECT_VALIDATION_COMPLETED = 1205,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_STARTED = 1300,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_STAGE_ENTERED = 1301,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_STAGE_COMPLETED = 1302,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_RETURNED = 1303,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_FUNCTION_RESULT = 1304,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_REPORT_RESULT = 1305,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_FUNCTION_REPORT_MATCHED = 1306,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_FUNCTION_REPORT_MISMATCH = 1307,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_REPORT_SUMMARY = 1308,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_STATUS_MAPPED = 1309,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_UNEXPECTED_ENUM = 1310,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_READY_PUBLISHED = 1311,
    CHATPAD_RUNTIME_EVENT_ORCHESTRATION_TERMINAL_CATEGORY = 1312,
    CHATPAD_RUNTIME_EVENT_READY_VALIDATION_STARTED = 1400,
    CHATPAD_RUNTIME_EVENT_READY_VALIDATION_PASSED = 1401,
    CHATPAD_RUNTIME_EVENT_READY_VALIDATION_FAILED = 1402,
    CHATPAD_RUNTIME_EVENT_READY_VALIDATION_MISSING_OBJECT = 1403,
    CHATPAD_RUNTIME_EVENT_READY_VALIDATION_INVARIANT_FAILED = 1404,
    CHATPAD_RUNTIME_EVENT_LIFECYCLE_INIT_STARTED = 1500,
    CHATPAD_RUNTIME_EVENT_LIFECYCLE_INIT_PASSED = 1501,
    CHATPAD_RUNTIME_EVENT_LIFECYCLE_INIT_FAILED = 1502,
    CHATPAD_RUNTIME_EVENT_MARK_DEVICE_CREATED_STARTED = 1503,
    CHATPAD_RUNTIME_EVENT_MARK_DEVICE_CREATED_PASSED = 1504,
    CHATPAD_RUNTIME_EVENT_MARK_DEVICE_CREATED_FAILED = 1505,
    CHATPAD_RUNTIME_EVENT_ROLLBACK_STARTED = 1600,
    CHATPAD_RUNTIME_EVENT_ROLLBACK_REASON = 1601,
    CHATPAD_RUNTIME_EVENT_ROLLBACK_OBJECT_SNAPSHOT_BEFORE = 1602,
    CHATPAD_RUNTIME_EVENT_ROLLBACK_COMPLETED = 1603,
    CHATPAD_RUNTIME_EVENT_ROLLBACK_OBJECT_SNAPSHOT_AFTER = 1604,
    CHATPAD_RUNTIME_EVENT_DEVICE_CONTEXT_CLEANUP_ENTERED = 1605,
    CHATPAD_RUNTIME_EVENT_DEVICE_CONTEXT_CLEANUP_SNAPSHOT = 1606,
    CHATPAD_RUNTIME_EVENT_DEVICE_CONTEXT_CLEANUP_COMPLETED = 1607,
    CHATPAD_RUNTIME_EVENT_CLEANUP_INVARIANT_VIOLATION = 1608,
    CHATPAD_RUNTIME_EVENT_PROHIBITED_COUNTERS_INITIALIZED = 1700,
    CHATPAD_RUNTIME_EVENT_TARGET_DISCOVERY_COUNTER_NONZERO = 1701,
    CHATPAD_RUNTIME_EVENT_TARGET_OPEN_COUNTER_NONZERO = 1702,
    CHATPAD_RUNTIME_EVENT_TARGET_ASSIGNMENT_COUNTER_NONZERO = 1703,
    CHATPAD_RUNTIME_EVENT_REQUEST_FORMAT_COUNTER_NONZERO = 1704,
    CHATPAD_RUNTIME_EVENT_REQUEST_REUSE_COUNTER_NONZERO = 1705,
    CHATPAD_RUNTIME_EVENT_REQUEST_SEND_COUNTER_NONZERO = 1706,
    CHATPAD_RUNTIME_EVENT_COMPLETION_COUNTER_NONZERO = 1707,
    CHATPAD_RUNTIME_EVENT_CANCELLATION_COUNTER_NONZERO = 1708,
    CHATPAD_RUNTIME_EVENT_PROTOCOL_TRAFFIC_COUNTER_NONZERO = 1709,
    CHATPAD_RUNTIME_EVENT_KEYBOARD_INJECTION_COUNTER_NONZERO = 1710,
    CHATPAD_RUNTIME_EVENT_D0_OWNER_OBSERVER_COUNTER_NONZERO = 1711,
    CHATPAD_RUNTIME_EVENT_REMOVAL_RUNDOWN_COUNTER_NONZERO = 1712,
    CHATPAD_RUNTIME_EVENT_PROHIBITED_COUNTERS_FINAL_SNAPSHOT = 1713,
    CHATPAD_RUNTIME_EVENT_ATTEMPT_ID_WRAPAROUND = 1800,
    CHATPAD_RUNTIME_EVENT_EVENT_SEQUENCE_GAP_DETECTED = 1801,
    CHATPAD_RUNTIME_EVENT_UNEXPECTED_STATUS_MAPPING = 1802,
    CHATPAD_RUNTIME_EVENT_OBJECT_SNAPSHOT_INCONSISTENT = 1803,
    CHATPAD_RUNTIME_EVENT_COUNTER_OVERFLOW = 1804,
    CHATPAD_RUNTIME_EVENT_TRACE_SCHEMA_VERSION_MISMATCH = 1805,
    CHATPAD_RUNTIME_EVENT_DEVICE_ADD_SUCCESS = 1900,
    CHATPAD_RUNTIME_EVENT_DEVICE_ADD_FAILURE = 1901,
    CHATPAD_RUNTIME_EVENT_DEVICE_ADD_FINAL_SUMMARY = 1902,
    CHATPAD_RUNTIME_EVENT_DEVICE_ADD_RETURNED_STATUS = 1903
} ChatpadRuntimeTraceEventId;

typedef enum ChatpadRuntimeStatusClass {
    CHATPAD_RUNTIME_STATUS_CLASS_NONE = 0,
    CHATPAD_RUNTIME_STATUS_CLASS_SUCCESS = 1,
    CHATPAD_RUNTIME_STATUS_CLASS_INVALID_PARAMETER = 2,
    CHATPAD_RUNTIME_STATUS_CLASS_INVALID_DEVICE_STATE = 3,
    CHATPAD_RUNTIME_STATUS_CLASS_INTEGER_OVERFLOW = 4,
    CHATPAD_RUNTIME_STATUS_CLASS_DEVICE_BUSY = 5,
    CHATPAD_RUNTIME_STATUS_CLASS_FRAMEWORK_FAILURE = 6,
    CHATPAD_RUNTIME_STATUS_CLASS_OTHER_FAILURE = 7
} ChatpadRuntimeStatusClass;

typedef enum ChatpadRuntimeTraceKeyword {
    CHATPAD_TRACE_DRIVER_ENTRY = 1,
    CHATPAD_TRACE_DEVICE_ADD = 2,
    CHATPAD_TRACE_OWNER = 3,
    CHATPAD_TRACE_ORCHESTRATION = 4,
    CHATPAD_TRACE_READINESS = 5,
    CHATPAD_TRACE_LIFECYCLE = 6,
    CHATPAD_TRACE_CLEANUP = 7,
    CHATPAD_TRACE_PROHIBITED_COUNTERS = 8,
    CHATPAD_TRACE_INVARIANT = 9,
    CHATPAD_TRACE_TERMINAL = 10
} ChatpadRuntimeTraceKeyword;

typedef struct ChatpadRuntimeProhibitedCounters {
    ULONG TargetDiscovery;
    ULONG TargetOpen;
    ULONG TargetAssignment;
    ULONG RequestFormat;
    ULONG RequestReuse;
    ULONG RequestSend;
    ULONG Completion;
    ULONG Cancellation;
    ULONG ProtocolTraffic;
    ULONG KeyboardInjection;
    ULONG D0OwnerObservation;
    ULONG RemovalRundownObservation;
} ChatpadRuntimeProhibitedCounters;

typedef struct ChatpadRuntimeObjectSnapshot {
    UCHAR BookkeepingLockPresent;
    UCHAR ReusableRequestPresent;
    UCHAR OutboundMemoryPresent;
    UCHAR InboundMemoryPresent;
    UCHAR OwnerReady;
    UCHAR Faulted;
    UCHAR ObjectGraphComplete;
    ULONG InitializationMask;
    ULONG StructuralReadyResult;
} ChatpadRuntimeObjectSnapshot;

static __inline const char *
ChatpadRuntimeTraceEventName(ChatpadRuntimeTraceEventId eventId)
{
    switch (eventId) {
    case CHATPAD_RUNTIME_EVENT_DRIVER_ENTRY_STARTED: return "DRIVER_ENTRY_STARTED";
    case CHATPAD_RUNTIME_EVENT_WDF_DRIVER_CREATE_ATTEMPTED: return "WDF_DRIVER_CREATE_ATTEMPTED";
    case CHATPAD_RUNTIME_EVENT_WDF_DRIVER_CREATE_FAILED: return "WDF_DRIVER_CREATE_FAILED";
    case CHATPAD_RUNTIME_EVENT_DRIVER_ENTRY_COMPLETED: return "DRIVER_ENTRY_COMPLETED";
    case CHATPAD_RUNTIME_EVENT_DEVICE_ADD_ENTERED: return "DEVICE_ADD_ENTERED";
    case CHATPAD_RUNTIME_EVENT_DEVICE_CREATE_ATTEMPTED: return "DEVICE_CREATE_ATTEMPTED";
    case CHATPAD_RUNTIME_EVENT_DEVICE_CREATE_FAILED: return "DEVICE_CREATE_FAILED";
    case CHATPAD_RUNTIME_EVENT_DEVICE_CONTEXT_INITIALIZING: return "DEVICE_CONTEXT_INITIALIZING";
    case CHATPAD_RUNTIME_EVENT_DEVICE_CONTEXT_READY: return "DEVICE_CONTEXT_READY";
    case CHATPAD_RUNTIME_EVENT_DEVICE_CREATE_COMPLETED: return "DEVICE_CREATE_COMPLETED";
    case CHATPAD_RUNTIME_EVENT_OWNER_STORAGE_INIT_STARTED: return "OWNER_STORAGE_INIT_STARTED";
    case CHATPAD_RUNTIME_EVENT_OWNER_STORAGE_INIT_COMPLETED: return "OWNER_STORAGE_INIT_COMPLETED";
    case CHATPAD_RUNTIME_EVENT_OWNER_STORAGE_INIT_FAILED: return "OWNER_STORAGE_INIT_FAILED";
    case CHATPAD_RUNTIME_EVENT_PRE_OBJECT_VALIDATION_STARTED: return "PRE_OBJECT_VALIDATION_STARTED";
    case CHATPAD_RUNTIME_EVENT_PRE_OBJECT_VALIDATION_FAILED: return "PRE_OBJECT_VALIDATION_FAILED";
    case CHATPAD_RUNTIME_EVENT_PRE_OBJECT_VALIDATION_COMPLETED: return "PRE_OBJECT_VALIDATION_COMPLETED";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_STARTED: return "ORCHESTRATION_STARTED";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_STAGE_ENTERED: return "ORCHESTRATION_STAGE_ENTERED";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_STAGE_COMPLETED: return "ORCHESTRATION_STAGE_COMPLETED";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_RETURNED: return "ORCHESTRATION_RETURNED";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_FUNCTION_RESULT: return "ORCHESTRATION_FUNCTION_RESULT";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_REPORT_RESULT: return "ORCHESTRATION_REPORT_RESULT";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_FUNCTION_REPORT_MATCHED: return "ORCHESTRATION_FUNCTION_REPORT_MATCHED";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_FUNCTION_REPORT_MISMATCH: return "ORCHESTRATION_FUNCTION_REPORT_MISMATCH";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_REPORT_SUMMARY: return "ORCHESTRATION_REPORT_SUMMARY";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_STATUS_MAPPED: return "ORCHESTRATION_STATUS_MAPPED";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_UNEXPECTED_ENUM: return "ORCHESTRATION_UNEXPECTED_ENUM";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_READY_PUBLISHED: return "ORCHESTRATION_READY_PUBLISHED";
    case CHATPAD_RUNTIME_EVENT_ORCHESTRATION_TERMINAL_CATEGORY: return "ORCHESTRATION_TERMINAL_CATEGORY";
    case CHATPAD_RUNTIME_EVENT_READY_VALIDATION_STARTED: return "READY_VALIDATION_STARTED";
    case CHATPAD_RUNTIME_EVENT_READY_VALIDATION_PASSED: return "READY_VALIDATION_PASSED";
    case CHATPAD_RUNTIME_EVENT_READY_VALIDATION_FAILED: return "READY_VALIDATION_FAILED";
    case CHATPAD_RUNTIME_EVENT_READY_VALIDATION_MISSING_OBJECT: return "READY_VALIDATION_MISSING_OBJECT";
    case CHATPAD_RUNTIME_EVENT_READY_VALIDATION_INVARIANT_FAILED: return "READY_VALIDATION_INVARIANT_FAILED";
    case CHATPAD_RUNTIME_EVENT_LIFECYCLE_INIT_STARTED: return "LIFECYCLE_INIT_STARTED";
    case CHATPAD_RUNTIME_EVENT_LIFECYCLE_INIT_PASSED: return "LIFECYCLE_INIT_PASSED";
    case CHATPAD_RUNTIME_EVENT_LIFECYCLE_INIT_FAILED: return "LIFECYCLE_INIT_FAILED";
    case CHATPAD_RUNTIME_EVENT_MARK_DEVICE_CREATED_STARTED: return "MARK_DEVICE_CREATED_STARTED";
    case CHATPAD_RUNTIME_EVENT_MARK_DEVICE_CREATED_PASSED: return "MARK_DEVICE_CREATED_PASSED";
    case CHATPAD_RUNTIME_EVENT_MARK_DEVICE_CREATED_FAILED: return "MARK_DEVICE_CREATED_FAILED";
    case CHATPAD_RUNTIME_EVENT_ROLLBACK_STARTED: return "ROLLBACK_STARTED";
    case CHATPAD_RUNTIME_EVENT_ROLLBACK_REASON: return "ROLLBACK_REASON";
    case CHATPAD_RUNTIME_EVENT_ROLLBACK_OBJECT_SNAPSHOT_BEFORE: return "ROLLBACK_OBJECT_SNAPSHOT_BEFORE";
    case CHATPAD_RUNTIME_EVENT_ROLLBACK_COMPLETED: return "ROLLBACK_COMPLETED";
    case CHATPAD_RUNTIME_EVENT_ROLLBACK_OBJECT_SNAPSHOT_AFTER: return "ROLLBACK_OBJECT_SNAPSHOT_AFTER";
    case CHATPAD_RUNTIME_EVENT_DEVICE_CONTEXT_CLEANUP_ENTERED: return "DEVICE_CONTEXT_CLEANUP_ENTERED";
    case CHATPAD_RUNTIME_EVENT_DEVICE_CONTEXT_CLEANUP_SNAPSHOT: return "DEVICE_CONTEXT_CLEANUP_SNAPSHOT";
    case CHATPAD_RUNTIME_EVENT_DEVICE_CONTEXT_CLEANUP_COMPLETED: return "DEVICE_CONTEXT_CLEANUP_COMPLETED";
    case CHATPAD_RUNTIME_EVENT_CLEANUP_INVARIANT_VIOLATION: return "CLEANUP_INVARIANT_VIOLATION";
    case CHATPAD_RUNTIME_EVENT_PROHIBITED_COUNTERS_INITIALIZED: return "PROHIBITED_COUNTERS_INITIALIZED";
    case CHATPAD_RUNTIME_EVENT_TARGET_DISCOVERY_COUNTER_NONZERO: return "TARGET_DISCOVERY_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_TARGET_OPEN_COUNTER_NONZERO: return "TARGET_OPEN_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_TARGET_ASSIGNMENT_COUNTER_NONZERO: return "TARGET_ASSIGNMENT_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_REQUEST_FORMAT_COUNTER_NONZERO: return "REQUEST_FORMAT_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_REQUEST_REUSE_COUNTER_NONZERO: return "REQUEST_REUSE_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_REQUEST_SEND_COUNTER_NONZERO: return "REQUEST_SEND_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_COMPLETION_COUNTER_NONZERO: return "COMPLETION_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_CANCELLATION_COUNTER_NONZERO: return "CANCELLATION_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_PROTOCOL_TRAFFIC_COUNTER_NONZERO: return "PROTOCOL_TRAFFIC_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_KEYBOARD_INJECTION_COUNTER_NONZERO: return "KEYBOARD_INJECTION_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_D0_OWNER_OBSERVER_COUNTER_NONZERO: return "D0_OWNER_OBSERVER_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_REMOVAL_RUNDOWN_COUNTER_NONZERO: return "REMOVAL_RUNDOWN_COUNTER_NONZERO";
    case CHATPAD_RUNTIME_EVENT_PROHIBITED_COUNTERS_FINAL_SNAPSHOT: return "PROHIBITED_COUNTERS_FINAL_SNAPSHOT";
    case CHATPAD_RUNTIME_EVENT_ATTEMPT_ID_WRAPAROUND: return "ATTEMPT_ID_WRAPAROUND";
    case CHATPAD_RUNTIME_EVENT_EVENT_SEQUENCE_GAP_DETECTED: return "EVENT_SEQUENCE_GAP_DETECTED";
    case CHATPAD_RUNTIME_EVENT_UNEXPECTED_STATUS_MAPPING: return "UNEXPECTED_STATUS_MAPPING";
    case CHATPAD_RUNTIME_EVENT_OBJECT_SNAPSHOT_INCONSISTENT: return "OBJECT_SNAPSHOT_INCONSISTENT";
    case CHATPAD_RUNTIME_EVENT_COUNTER_OVERFLOW: return "COUNTER_OVERFLOW";
    case CHATPAD_RUNTIME_EVENT_TRACE_SCHEMA_VERSION_MISMATCH: return "TRACE_SCHEMA_VERSION_MISMATCH";
    case CHATPAD_RUNTIME_EVENT_DEVICE_ADD_SUCCESS: return "DEVICE_ADD_SUCCESS";
    case CHATPAD_RUNTIME_EVENT_DEVICE_ADD_FAILURE: return "DEVICE_ADD_FAILURE";
    case CHATPAD_RUNTIME_EVENT_DEVICE_ADD_FINAL_SUMMARY: return "DEVICE_ADD_FINAL_SUMMARY";
    case CHATPAD_RUNTIME_EVENT_DEVICE_ADD_RETURNED_STATUS: return "DEVICE_ADD_RETURNED_STATUS";
    default: return "UNKNOWN_RUNTIME_TRACE_EVENT";
    }
}

static __inline ChatpadRuntimeStatusClass
ChatpadRuntimeClassifyStatus(NTSTATUS status)
{
    if (NT_SUCCESS(status)) {
        return CHATPAD_RUNTIME_STATUS_CLASS_SUCCESS;
    }
    switch (status) {
    case STATUS_INVALID_PARAMETER:
        return CHATPAD_RUNTIME_STATUS_CLASS_INVALID_PARAMETER;
    case STATUS_INVALID_DEVICE_STATE:
        return CHATPAD_RUNTIME_STATUS_CLASS_INVALID_DEVICE_STATE;
    case STATUS_INTEGER_OVERFLOW:
        return CHATPAD_RUNTIME_STATUS_CLASS_INTEGER_OVERFLOW;
    case STATUS_DEVICE_BUSY:
        return CHATPAD_RUNTIME_STATUS_CLASS_DEVICE_BUSY;
    default:
        return CHATPAD_RUNTIME_STATUS_CLASS_OTHER_FAILURE;
    }
}

static __inline ChatpadRuntimeObjectSnapshot
ChatpadRuntimeCaptureObjectSnapshot(
    const ChatpadKmdfActivationRequestOwner *owner,
    ULONG structuralReadyResult
    )
{
    ChatpadRuntimeObjectSnapshot snapshot;

    RtlZeroMemory(&snapshot, sizeof(snapshot));
    snapshot.StructuralReadyResult = structuralReadyResult;
    if (owner == NULL) {
        return snapshot;
    }

    snapshot.BookkeepingLockPresent = owner->BookkeepingLock != NULL ? 1u : 0u;
    snapshot.ReusableRequestPresent = owner->Request != NULL ? 1u : 0u;
    snapshot.OutboundMemoryPresent = owner->OutboundMemory != NULL ? 1u : 0u;
    snapshot.InboundMemoryPresent = owner->InboundMemory != NULL ? 1u : 0u;
    snapshot.OwnerReady =
        (owner->InitializationMask & CHATPAD_KMDF_REQUEST_OWNER_INIT_OWNER_READY) != 0u ? 1u : 0u;
    snapshot.Faulted =
        (owner->InitializationMask & CHATPAD_KMDF_REQUEST_OWNER_INIT_FAULTED) != 0u ? 1u : 0u;
    snapshot.ObjectGraphComplete =
        (snapshot.BookkeepingLockPresent != 0u &&
         snapshot.ReusableRequestPresent != 0u &&
         snapshot.OutboundMemoryPresent != 0u &&
         snapshot.InboundMemoryPresent != 0u) ? 1u : 0u;
    snapshot.InitializationMask = owner->InitializationMask;
    return snapshot;
}

static __inline uint64_t
ChatpadRuntimeNextOwnerSequence(ChatpadKmdfActivationRequestOwner *owner)
{
    if (owner == NULL) {
        return 0u;
    }
    owner->DiagnosticTraceSequence += 1u;
    return owner->DiagnosticTraceSequence;
}

#define CHATPAD_RUNTIME_TRACE_EVENT_FORMAT \
    "EventId=%lu EventName=%s AttemptId=%I64u Sequence=%I64u SchemaVersion=%lu StatusClass=%lu NtStatus=0x%08X Stage=%lu Data0=%lu Data1=%lu"

#define CHATPAD_RUNTIME_TRACE_SNAPSHOT_FORMAT \
    "EventId=%lu EventName=%s AttemptId=%I64u Sequence=%I64u SchemaVersion=%lu StatusClass=%lu NtStatus=0x%08X BookkeepingLockPresent=%u ReusableRequestPresent=%u OutboundMemoryPresent=%u InboundMemoryPresent=%u OwnerReady=%u Faulted=%u ObjectGraphComplete=%u InitializationMask=0x%08X StructuralReadyResult=%lu"

#define CHATPAD_RUNTIME_TRACE_COUNTERS_FORMAT \
    "EventId=%lu EventName=%s AttemptId=%I64u Sequence=%I64u SchemaVersion=%lu TargetDiscovery=%lu TargetOpen=%lu TargetAssignment=%lu RequestFormat=%lu RequestReuse=%lu RequestSend=%lu Completion=%lu Cancellation=%lu ProtocolTraffic=%lu KeyboardInjection=%lu D0OwnerObservation=%lu RemovalRundownObservation=%lu"
