using namespace System
[CmdletBinding()]param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
[void][Reflection.Assembly]::LoadWithPartialName('System.Security')
$root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$modulePath=Join-Path $root 'tools\ExactInstance\ChatpadLocalDevelopmentTestSigning.psm1';$invokePath=Join-Path $root 'tools\Invoke-ChatpadLocalDevelopmentTestSigning.ps1';$module=[IO.File]::ReadAllText($modulePath);$invoke=[IO.File]::ReadAllText($invokePath);$all=$module+"`n"+$invoke;$script:t=0;$script:a=0
function A([bool]$c,[string]$m){$script:a++;if(-not$c){throw $m}};function T([string]$n,[scriptblock]$b){&$b;$script:t++;"PASS: $n"};function Parse([string]$p){$e=$null;$x=$null;[Management.Automation.Language.Parser]::ParseFile($p,[ref]$x,[ref]$e)|Out-Null;@($e)}
$artifact=Join-Path $root 'artifacts\task-8i-p1b-ld-s1-self-test-signed-package';$final=Join-Path $artifact 'final';$cat=Join-Path $final 'ChatpadFilterExtension.cat';$thumb='885ADDC8018AC58E19B14668ACDAC9072BB6AE15'
T 'sources parse'{A (@(Parse $modulePath).Count-eq0) 'module';A (@(Parse $invokePath).Count-eq0) 'invoke'}
T 'single recovery export'{A ([regex]::Matches($module,'Export-ModuleMember').Count-eq1) 'count';A ($module-match'Complete-ChatpadPostCatRecovery') 'name'}
T 'exact S1R2 authorization only'{A ($module-match'ValidateScript\(\{\$_-ceq\$script:Authorization\}\)') 'module';A ($invoke-match'\$Authorization-cne\$exact') 'invoke';A ($all-notmatch'AUTHORIZE_EXISTING_LOCAL_TEST_CERTIFICATE_REUSE_FOR_CATALOG_AND_PACKAGE_FINALIZATION|AUTHORIZE_LOCAL_SELF_TEST_CERTIFICATE_CREATION_AND_PACKAGE_SIGNING') 'old'}
T 'Inf2Cat and signing structurally prohibited'{foreach($x in @('Inf2Cat.exe','signtool.exe',"@('sign'",'New-SelfSignedCertificate')){A ($all-notmatch[regex]::Escape($x)) "forbidden $x"}}
T 'certificate mutation export and private-key access absent'{foreach($x in @('Remove-Item Cert:','Import-Certificate','Export-Certificate','Export-PfxCertificate','GetRSAPrivateKey','.PrivateKey','CngExportPolicies')){A ($all-notmatch[regex]::Escape($x)) "forbidden $x"}}
T 'host driver device and native operations absent'{foreach($x in @('bcdedit','Restart-Computer','pnputil','devcon','Get-PnpDevice','Win32_PnPEntity','Invoke-ChatpadOneShotLiveNativeApply','DllImport','Add-Type')){A ($all-notmatch[regex]::Escape($x)) "forbidden $x"}}
T 'case-corrected retained CAT exact'{A ((Get-Item $cat).Name-ceq'ChatpadFilterExtension.cat') 'name';A ((Get-Item $cat).Length-eq2961) 'size';A ((Get-FileHash $cat -Algorithm SHA256).Hash-ceq'B34C084E60020B401518A9259E476AFC22980DC2B51311EE053F1FF410DDCFF4') 'hash';A (-not(Test-Path (Join-Path $final 'chatpadfilterextension.cat.casefix.tmp'))) 'temp absent'}
T 'CAT cryptographic signature exact'{$cms=[Security.Cryptography.Pkcs.SignedCms]::new();$cms.Decode([IO.File]::ReadAllBytes($cat));$cms.CheckSignature($true);A ($cms.SignerInfos.Count-eq1) 'signers';A ($cms.SignerInfos[0].Certificate.Thumbprint-ceq$thumb) 'thumb';A ($cms.SignerInfos[0].UnsignedAttributes.Count-eq0) 'timestamp'}
T 'catalog Authenticode and members bound by retained logs'{foreach($x in @(@('signtool-remediation-verify-cat.log',867,'E79F3E1E20FBFADCF346F796A1DA66AEF5126EC4573CC434D6B5254297C8F6F1'),@('signtool-remediation-member-ChatpadFilter.sys.log',1088,'D29E410321176099CC8278BFD7FC1A548AACDE393FB1F607EB31C2EBB0EFB362'),@('signtool-remediation-member-ChatpadFilterExtension.inf.log',1115,'39998046CD0766AA337733BE95630C6930D6094D011E4DC1F7987304A44A7BC0'))){$p=Join-Path $artifact ('logs\'+$x[0]);A ((Get-Item $p).Length-eq$x[1]) $x[0];A ((Get-FileHash $p -Algorithm SHA256).Hash-ceq$x[2]) $x[0]}}
T 'signed SYS exact and unchanged'{$p=Join-Path $final 'ChatpadFilter.sys';A ((Get-Item $p).Length-eq42856) 'size';A ((Get-FileHash $p -Algorithm SHA256).Hash-ceq'B1FCF99F0B7631E83397396024E91213A4FCF9B145CCC97E01E6684562DC7190') 'hash';$s=Get-AuthenticodeSignature $p;A ($s.SignerCertificate.Thumbprint-ceq$thumb-and$s.Status-notin@('HashMismatch','NotSigned')-and$null-eq$s.TimeStamperCertificate) 'signature'}
T 'certificate read-only metadata exact'{$m=@(Get-ChildItem Cert:\CurrentUser\My|Where-Object{$_.Subject-ceq'CN=Chatpad Super Driver Local Development Test Signing'});A ($m.Count-eq1) 'count';A ($m[0].Thumbprint-ceq$thumb-and$m[0].SerialNumber-ceq'555B00DC46D24680444994B5A16E6E7C'-and$m[0].HasPrivateKey) 'metadata'}
T 'public CER exact and private-key free'{$p=Join-Path $root 'tools\ExactInstance\certificates\ChatpadLocalDevelopmentTestSigning.cer';A ((Get-Item $p).Length-eq1104) 'size';A ((Get-FileHash $p -Algorithm SHA256).Hash-ceq'300238DB21F1ECD2F2C2E9F3A03EFF0147CBC419D474B1B3B89433569D5E6C96') 'hash';$c=[Security.Cryptography.X509Certificates.X509Certificate2]::new($p);A (-not$c.HasPrivateKey-and$c.Thumbprint-ceq$thumb) 'cert'}
T 'both partial evidence identities exact'{$p1=Join-Path $artifact 'logs\partial-state.json';$p2=Join-Path $artifact 'logs\remediation-partial-state.json';A ((Get-FileHash $p1 -Algorithm SHA256).Hash-ceq'1ECA020209770FA84EF9EDB2FD5B17318304A93134F382654F5A71A9A3C49C61') 'S1';A ((Get-Item $p2).Length-eq3366-and(Get-FileHash $p2 -Algorithm SHA256).Hash-ceq'A8262051FE1248E2E027EF1CE73FD6397849CA46921F7116190EF6D11CF234D9') 'S1R1'}
T 'two-step case rename source exact'{A ($module-match'Rename-Item -LiteralPath \$script:CurrentCat -NewName ''ChatpadFilterExtension.cat.casefix.tmp''') 'first';A ($module-match'Rename-Item -LiteralPath \$script:TemporaryCat -NewName ''ChatpadFilterExtension.cat''') 'second'}
T 'case rename fixture preserves bytes and hash'{$d=Join-Path ([IO.Path]::GetTempPath()) ('chatpad-case-'+[guid]::NewGuid().ToString('N'));[void](New-Item -ItemType Directory $d);try{$p=Join-Path $d 'chatpadfilterextension.cat';[IO.File]::WriteAllBytes($p,[byte[]](1,2,3,4));$h=(Get-FileHash $p -Algorithm SHA256).Hash;Rename-Item $p -NewName 'ChatpadFilterExtension.cat.casefix.tmp';Rename-Item (Join-Path $d 'ChatpadFilterExtension.cat.casefix.tmp') -NewName 'ChatpadFilterExtension.cat';$e=@(Get-ChildItem $d);A ($e.Count-eq1-and$e[0].Name-ceq'ChatpadFilterExtension.cat') 'name';A ((Get-FileHash $e[0].FullName -Algorithm SHA256).Hash-ceq$h) 'hash'}finally{Remove-Item $d -Recurse -Force}}
T 'missing pre-sign identity is explicit and not fabricated'{foreach($x in @("state='NOT_RETAINED_BEFORE_IN_PLACE_SIGNING'","ordinary_sha256='NOT_AVAILABLE'","reconstruction_attempted=`$false",'RAW_PRE_SIGN_CATALOG_BYTE_IDENTITY_CANNOT_BE_INDEPENDENTLY_REPRODUCED_FROM_RETAINED_STATE')){A ($module-match[regex]::Escape($x)) $x};A ($module-notmatch'generated_unsigned_catalog_pre_sign_identity[^\r\n]+[0-9A-F]{64}') 'fabricated'}
T 'final inventory and temporary absence enforced'{A ($module-match"Compare-Object @\('ChatpadFilter.sys','ChatpadFilterExtension.cat','ChatpadFilterExtension.inf'\)") 'inventory';A ($module-match'temporary_path_retained=\$false') 'temp';A ($module-match'lowercase_entry_retained=\$false') 'lower'}
T 'CAT byte and signature equality enforced'{A ($module-match'\$before\.identity\.sha256-cne\$after\.identity\.sha256') 'hash';A ($module-match'\$before\.authenticode_sha256-cne\$after\.authenticode_sha256') 'auth';A ($module-match'\$before\.signer_thumbprint-cne\$after\.signer_thumbprint') 'signer'}
T 'public CER force-add exact and unique'{A ($module-match"git add -f -- 'tools/ExactInstance/certificates/ChatpadLocalDevelopmentTestSigning.cer'") 'path';A ([regex]::Matches($module,'git add -f').Count-eq1) 'count'}
T 'S1R2 zero and cumulative counters exact'{foreach($x in @('inf2cat_invocation=0','catalog_generation=0','cat_signing=0','sys_signing=0','private_key_access=0','valid_three_argument_inf2cat_invocation=1','case_only_catalog_rename_steps=2')){A ($module-match[regex]::Escape($x)) $x}}
T 'package state cannot be overclaimed'{foreach($x in @('certificate_not_trusted=$true','not_staged=$true','not_installed=$true','not_loaded=$true','no_device_query=$true','no_native_execution=$true')){A ($module-match[regex]::Escape($x)) $x}}
T 'final evidence and contract schemas agree'{$e=Get-Content (Join-Path $root 'docs\evidence\self-test-signed-local-development-package-task-8i-p1b-ld-s1.json') -Raw|ConvertFrom-Json;$c=Get-Content (Join-Path $root 'tools\ExactInstance\contracts\chatpad-live-apply-self-test-signed-package-plan.json') -Raw|ConvertFrom-Json;$schemas=@('chatpad-self-test-signed-local-development-package-v1','chatpad-live-apply-self-test-signed-package-plan-v1');$i=0;foreach($x in @($e,$c)){A ($x.schema-ceq$schemas[$i++]) 'schema';A ($x.status-ceq'SELF_TEST_SIGNED_LOCAL_DEVELOPMENT_PACKAGE_FINALIZED_FROM_CONTROLLED_POST_CAT_RECOVERY_CERTIFICATE_NOT_TRUSTED_TESTSIGNING_CONFIGURED_REBOOT_PENDING_PACKAGE_NOT_STAGED_NOT_INSTALLED_NOT_LOADED') 'status';A ($x.readiness-ceq'READY_FOR_SELF_TEST_SIGNED_PACKAGE_INDEPENDENT_AUDIT_ONLY') 'readiness';A ($x.generated_unsigned_catalog_pre_sign_identity.state-ceq'NOT_RETAINED_BEFORE_IN_PLACE_SIGNING'-and$x.generated_unsigned_catalog_pre_sign_identity.ordinary_sha256-ceq'NOT_AVAILABLE'-and(-not$x.generated_unsigned_catalog_pre_sign_identity.reconstruction_attempted)) 'limitation'}}
T 'final evidence inventory and counters exact'{$e=Get-Content (Join-Path $root 'docs\evidence\self-test-signed-local-development-package-task-8i-p1b-ld-s1.json') -Raw|ConvertFrom-Json;A ($e.final_package_inventory.Count-eq3) 'inventory';A ((@($e.final_package_inventory.path|Split-Path -Leaf)-join',')-ceq'ChatpadFilter.sys,ChatpadFilterExtension.cat,ChatpadFilterExtension.inf') 'order';A ($e.cumulative_mutation_counters.sys_signing-eq1-and$e.cumulative_mutation_counters.valid_three_argument_inf2cat_invocation-eq1-and$e.cumulative_mutation_counters.cat_signing-eq1) 'cumulative';A ($e.s1r2_mutation_counters.inf2cat_invocation-eq0-and$e.s1r2_mutation_counters.cat_signing-eq0-and$e.s1r2_mutation_counters.private_key_access-eq0) 'recovery'}
T 'module hash finalized and bound'{A ($invoke-notmatch'MODULE_SHA256_TO_BE_FINALIZED') 'placeholder';$h=(Get-FileHash $modulePath -Algorithm SHA256).Hash;$b=[regex]::Match($invoke,"moduleSha256='([0-9A-F]{64})'").Groups[1].Value;A ($h-ceq$b) 'binding'}
"S1R2 focused static/read-only suite: $script:t tests / $script:a assertions"
